// Mocks generated by Mockito 5.4.6 from annotations
// in partner/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;
import 'dart:io' as _i34;
import 'dart:typed_data' as _i31;
import 'dart:ui' as _i20;

import 'package:flutter/material.dart' as _i18;
import 'package:image_cropper/image_cropper.dart' as _i41;
import 'package:image_picker/image_picker.dart' as _i40;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:partner/core/enums/user_role.dart' as _i23;
import 'package:partner/core/models/appointment/appointment.dart' as _i6;
import 'package:partner/core/models/appointment/appointment_history_entry.dart'
    as _i28;
import 'package:partner/core/models/appointment/time_slot.dart' as _i27;
import 'package:partner/core/models/auth/user.dart' as _i2;
import 'package:partner/core/models/clinic/bulk_create_result.dart' as _i11;
import 'package:partner/core/models/clinic/clinic.dart' as _i12;
import 'package:partner/core/models/clinic/clinic_branding.dart' as _i13;
import 'package:partner/core/models/clinic/send_result.dart' as _i15;
import 'package:partner/core/models/document/document.dart' as _i10;
import 'package:partner/core/models/medical/medical_record.dart' as _i7;
import 'package:partner/core/models/medical/prescription.dart' as _i8;
import 'package:partner/core/models/medical/vaccination.dart' as _i9;
import 'package:partner/core/models/pagination.dart' as _i3;
import 'package:partner/core/models/pet/pet.dart' as _i4;
import 'package:partner/core/models/pet_owner.dart' as _i5;
import 'package:partner/core/models/reminder/reminder.dart' as _i14;
import 'package:partner/services/api_client.dart' as _i21;
import 'package:partner/services/appointment_service.dart' as _i26;
import 'package:partner/services/auth_service.dart' as _i22;
import 'package:partner/services/clinic_service.dart' as _i36;
import 'package:partner/services/connectivity_service.dart' as _i38;
import 'package:partner/services/document_service.dart' as _i33;
import 'package:partner/services/image_upload_service.dart' as _i39;
import 'package:partner/services/medical_record_service.dart' as _i29;
import 'package:partner/services/pet_owner_service.dart' as _i25;
import 'package:partner/services/pet_service.dart' as _i24;
import 'package:partner/services/prescription_service.dart' as _i30;
import 'package:partner/services/reminder_service.dart' as _i37;
import 'package:partner/services/user_service.dart' as _i35;
import 'package:partner/services/vaccination_service.dart' as _i32;
import 'package:stacked_services/stacked_services.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResponse_1<T> extends _i1.SmartFake
    implements _i3.PaginatedResponse<T> {
  _FakePaginatedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePet_2 extends _i1.SmartFake implements _i4.Pet {
  _FakePet_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePetOwner_3 extends _i1.SmartFake implements _i5.PetOwner {
  _FakePetOwner_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppointment_4 extends _i1.SmartFake implements _i6.Appointment {
  _FakeAppointment_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMedicalRecord_5 extends _i1.SmartFake implements _i7.MedicalRecord {
  _FakeMedicalRecord_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrescription_6 extends _i1.SmartFake implements _i8.Prescription {
  _FakePrescription_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVaccination_7 extends _i1.SmartFake implements _i9.Vaccination {
  _FakeVaccination_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_8 extends _i1.SmartFake implements _i10.Document {
  _FakeDocument_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBulkCreateResult_9 extends _i1.SmartFake
    implements _i11.BulkCreateResult {
  _FakeBulkCreateResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClinic_10 extends _i1.SmartFake implements _i12.Clinic {
  _FakeClinic_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClinicBranding_11 extends _i1.SmartFake
    implements _i13.ClinicBranding {
  _FakeClinicBranding_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReminder_12 extends _i1.SmartFake implements _i14.Reminder {
  _FakeReminder_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSendResult_13 extends _i1.SmartFake implements _i15.SendResult {
  _FakeSendResult_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i16.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i18.GlobalKey<_i18.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i18.GlobalKey<_i18.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i16.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<T?>? navigateWithTransition<T>(
    _i18.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i18.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i16.Transition? transitionClass,
    _i16.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? replaceWithTransition<T>(
    _i18.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i18.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i16.Transition? transitionClass,
    _i16.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i18.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i18.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? navigateToView<T>(
    _i18.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i18.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i16.Transition? transition,
    _i16.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i18.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? clearStackAndShowView<T>(
    _i18.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? clearTillFirstAndShowView<T>(
    _i18.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);

  @override
  _i19.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i18.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i19.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i16.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i16.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<_i16.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i19.Future<_i16.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i19.Future<_i16.SheetResponse<dynamic>?>.value(),
      ) as _i19.Future<_i16.SheetResponse<dynamic>?>);

  @override
  _i19.Future<_i16.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i20.Color? barrierColor = const _i20.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i19.Future<_i16.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i19.Future<_i16.SheetResponse<T>?>.value(),
      ) as _i19.Future<_i16.SheetResponse<T>?>);

  @override
  void completeSheet(_i16.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i16.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i16.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i18.Widget Function(
      _i18.BuildContext,
      _i16.DialogRequest<dynamic>,
      dynamic Function(_i16.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<_i16.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i20.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i20.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i18.RouteSettings? routeSettings,
    _i18.GlobalKey<_i18.NavigatorState>? navigatorKey,
    _i16.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i19.Future<_i16.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i19.Future<_i16.DialogResponse<dynamic>?>.value(),
      ) as _i19.Future<_i16.DialogResponse<dynamic>?>);

  @override
  _i19.Future<_i16.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i20.Color? barrierColor = const _i20.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i18.RouteSettings? routeSettings,
    _i18.GlobalKey<_i18.NavigatorState>? navigatorKey,
    _i18.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i19.Future<_i16.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i19.Future<_i16.DialogResponse<T>?>.value(),
      ) as _i19.Future<_i16.DialogResponse<T>?>);

  @override
  _i19.Future<_i16.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i20.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i20.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i18.RouteSettings? routeSettings,
    _i16.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i19.Future<_i16.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i19.Future<_i16.DialogResponse<dynamic>?>.value(),
      ) as _i19.Future<_i16.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i16.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i21.ApiClient {
  @override
  _i19.Future<dynamic> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {#queryParameters: queryParameters},
        ),
        returnValue: _i19.Future<dynamic>.value(),
        returnValueForMissingStub: _i19.Future<dynamic>.value(),
      ) as _i19.Future<dynamic>);

  @override
  _i19.Future<dynamic> post(
    String? path, {
    dynamic data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {#data: data},
        ),
        returnValue: _i19.Future<dynamic>.value(),
        returnValueForMissingStub: _i19.Future<dynamic>.value(),
      ) as _i19.Future<dynamic>);

  @override
  _i19.Future<dynamic> put(
    String? path, {
    dynamic data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {#data: data},
        ),
        returnValue: _i19.Future<dynamic>.value(),
        returnValueForMissingStub: _i19.Future<dynamic>.value(),
      ) as _i19.Future<dynamic>);

  @override
  _i19.Future<dynamic> patch(
    String? path, {
    dynamic data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {#data: data},
        ),
        returnValue: _i19.Future<dynamic>.value(),
        returnValueForMissingStub: _i19.Future<dynamic>.value(),
      ) as _i19.Future<dynamic>);

  @override
  _i19.Future<dynamic> delete(String? path) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
        ),
        returnValue: _i19.Future<dynamic>.value(),
        returnValueForMissingStub: _i19.Future<dynamic>.value(),
      ) as _i19.Future<dynamic>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i22.AuthService {
  @override
  List<_i23.UserRole> get availableRoles => (super.noSuchMethod(
        Invocation.getter(#availableRoles),
        returnValue: <_i23.UserRole>[],
        returnValueForMissingStub: <_i23.UserRole>[],
      ) as List<_i23.UserRole>);

  @override
  bool get hasMultipleRoles => (super.noSuchMethod(
        Invocation.getter(#hasMultipleRoles),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i19.Future<void> loadUserFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #loadUserFromStorage,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i2.User> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i19.Future<_i2.User>);

  @override
  _i19.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i2.User> switchRole(_i23.UserRole? newRole) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchRole,
          [newRole],
        ),
        returnValue: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #switchRole,
            [newRole],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #switchRole,
            [newRole],
          ),
        )),
      ) as _i19.Future<_i2.User>);

  @override
  _i19.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i2.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i19.Future<_i2.User?>.value(),
        returnValueForMissingStub: _i19.Future<_i2.User?>.value(),
      ) as _i19.Future<_i2.User?>);

  @override
  _i19.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i19.Future<bool>.value(false),
        returnValueForMissingStub: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  _i19.Future<_i23.UserRole?> getUserRole() => (super.noSuchMethod(
        Invocation.method(
          #getUserRole,
          [],
        ),
        returnValue: _i19.Future<_i23.UserRole?>.value(),
        returnValueForMissingStub: _i19.Future<_i23.UserRole?>.value(),
      ) as _i19.Future<_i23.UserRole?>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetService extends _i1.Mock implements _i24.PetService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i4.Pet>> getPets({
    int? page = 1,
    int? limit = 20,
    String? species,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPets,
          [],
          {
            #page: page,
            #limit: limit,
            #species: species,
            #isActive: isActive,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i4.Pet>>.value(
            _FakePaginatedResponse_1<_i4.Pet>(
          this,
          Invocation.method(
            #getPets,
            [],
            {
              #page: page,
              #limit: limit,
              #species: species,
              #isActive: isActive,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i4.Pet>>.value(
                _FakePaginatedResponse_1<_i4.Pet>(
          this,
          Invocation.method(
            #getPets,
            [],
            {
              #page: page,
              #limit: limit,
              #species: species,
              #isActive: isActive,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i4.Pet>>);

  @override
  _i19.Future<_i4.Pet> getPetById(String? petId) => (super.noSuchMethod(
        Invocation.method(
          #getPetById,
          [petId],
        ),
        returnValue: _i19.Future<_i4.Pet>.value(_FakePet_2(
          this,
          Invocation.method(
            #getPetById,
            [petId],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i4.Pet>.value(_FakePet_2(
          this,
          Invocation.method(
            #getPetById,
            [petId],
          ),
        )),
      ) as _i19.Future<_i4.Pet>);

  @override
  _i19.Future<_i4.Pet> createPet(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPet,
          [data],
        ),
        returnValue: _i19.Future<_i4.Pet>.value(_FakePet_2(
          this,
          Invocation.method(
            #createPet,
            [data],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i4.Pet>.value(_FakePet_2(
          this,
          Invocation.method(
            #createPet,
            [data],
          ),
        )),
      ) as _i19.Future<_i4.Pet>);

  @override
  _i19.Future<_i4.Pet> updatePet(
    String? petId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePet,
          [
            petId,
            data,
          ],
        ),
        returnValue: _i19.Future<_i4.Pet>.value(_FakePet_2(
          this,
          Invocation.method(
            #updatePet,
            [
              petId,
              data,
            ],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i4.Pet>.value(_FakePet_2(
          this,
          Invocation.method(
            #updatePet,
            [
              petId,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i4.Pet>);

  @override
  _i19.Future<void> deletePet(String? petId) => (super.noSuchMethod(
        Invocation.method(
          #deletePet,
          [petId],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<Map<String, dynamic>> getPetMedicalSummary(String? petId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPetMedicalSummary,
          [petId],
        ),
        returnValue:
            _i19.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i19.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i19.Future<Map<String, dynamic>>);
}

/// A class which mocks [PetOwnerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetOwnerService extends _i1.Mock implements _i25.PetOwnerService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i5.PetOwner>> getPetOwners({
    int? page = 1,
    int? limit = 20,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPetOwners,
          [],
          {
            #page: page,
            #limit: limit,
            #search: search,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i5.PetOwner>>.value(
            _FakePaginatedResponse_1<_i5.PetOwner>(
          this,
          Invocation.method(
            #getPetOwners,
            [],
            {
              #page: page,
              #limit: limit,
              #search: search,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i5.PetOwner>>.value(
                _FakePaginatedResponse_1<_i5.PetOwner>(
          this,
          Invocation.method(
            #getPetOwners,
            [],
            {
              #page: page,
              #limit: limit,
              #search: search,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i5.PetOwner>>);

  @override
  _i19.Future<_i5.PetOwner> getPetOwnerById(String? ownerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPetOwnerById,
          [ownerId],
        ),
        returnValue: _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #getPetOwnerById,
            [ownerId],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #getPetOwnerById,
            [ownerId],
          ),
        )),
      ) as _i19.Future<_i5.PetOwner>);

  @override
  _i19.Future<_i5.PetOwner> createPetOwner(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPetOwner,
          [data],
        ),
        returnValue: _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #createPetOwner,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #createPetOwner,
            [data],
          ),
        )),
      ) as _i19.Future<_i5.PetOwner>);

  @override
  _i19.Future<_i5.PetOwner> updatePetOwner(
    String? ownerId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePetOwner,
          [
            ownerId,
            data,
          ],
        ),
        returnValue: _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #updatePetOwner,
            [
              ownerId,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #updatePetOwner,
            [
              ownerId,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i5.PetOwner>);

  @override
  _i19.Future<_i5.PetOwner?> lookupByPhone(String? phone) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupByPhone,
          [phone],
        ),
        returnValue: _i19.Future<_i5.PetOwner?>.value(),
        returnValueForMissingStub: _i19.Future<_i5.PetOwner?>.value(),
      ) as _i19.Future<_i5.PetOwner?>);

  @override
  _i19.Future<_i5.PetOwner> quickCreate(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #quickCreate,
          [data],
        ),
        returnValue: _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #quickCreate,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i5.PetOwner>.value(_FakePetOwner_3(
          this,
          Invocation.method(
            #quickCreate,
            [data],
          ),
        )),
      ) as _i19.Future<_i5.PetOwner>);
}

/// A class which mocks [AppointmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentService extends _i1.Mock
    implements _i26.AppointmentService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i6.Appointment>> getAppointments({
    int? page = 1,
    int? limit = 20,
    String? status,
    String? petId,
    String? veterinarianId,
    String? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointments,
          [],
          {
            #page: page,
            #limit: limit,
            #status: status,
            #petId: petId,
            #veterinarianId: veterinarianId,
            #date: date,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i6.Appointment>>.value(
            _FakePaginatedResponse_1<_i6.Appointment>(
          this,
          Invocation.method(
            #getAppointments,
            [],
            {
              #page: page,
              #limit: limit,
              #status: status,
              #petId: petId,
              #veterinarianId: veterinarianId,
              #date: date,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i6.Appointment>>.value(
                _FakePaginatedResponse_1<_i6.Appointment>(
          this,
          Invocation.method(
            #getAppointments,
            [],
            {
              #page: page,
              #limit: limit,
              #status: status,
              #petId: petId,
              #veterinarianId: veterinarianId,
              #date: date,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i6.Appointment>>);

  @override
  _i19.Future<_i6.Appointment> getAppointmentById(String? appointmentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointmentById,
          [appointmentId],
        ),
        returnValue: _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #getAppointmentById,
            [appointmentId],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #getAppointmentById,
            [appointmentId],
          ),
        )),
      ) as _i19.Future<_i6.Appointment>);

  @override
  _i19.Future<_i6.Appointment> createAppointment(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAppointment,
          [data],
        ),
        returnValue: _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #createAppointment,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #createAppointment,
            [data],
          ),
        )),
      ) as _i19.Future<_i6.Appointment>);

  @override
  _i19.Future<_i6.Appointment> updateAppointment(
    String? appointmentId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppointment,
          [
            appointmentId,
            data,
          ],
        ),
        returnValue: _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #updateAppointment,
            [
              appointmentId,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #updateAppointment,
            [
              appointmentId,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i6.Appointment>);

  @override
  _i19.Future<_i6.Appointment> updateAppointmentStatus(
    String? appointmentId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppointmentStatus,
          [
            appointmentId,
            status,
          ],
        ),
        returnValue: _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #updateAppointmentStatus,
            [
              appointmentId,
              status,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #updateAppointmentStatus,
            [
              appointmentId,
              status,
            ],
          ),
        )),
      ) as _i19.Future<_i6.Appointment>);

  @override
  _i19.Future<_i6.Appointment> approveAppointment(String? appointmentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveAppointment,
          [appointmentId],
        ),
        returnValue: _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #approveAppointment,
            [appointmentId],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i6.Appointment>.value(_FakeAppointment_4(
          this,
          Invocation.method(
            #approveAppointment,
            [appointmentId],
          ),
        )),
      ) as _i19.Future<_i6.Appointment>);

  @override
  _i19.Future<_i3.PaginatedResponse<_i6.Appointment>> getPendingAppointments({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingAppointments,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i6.Appointment>>.value(
            _FakePaginatedResponse_1<_i6.Appointment>(
          this,
          Invocation.method(
            #getPendingAppointments,
            [],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i6.Appointment>>.value(
                _FakePaginatedResponse_1<_i6.Appointment>(
          this,
          Invocation.method(
            #getPendingAppointments,
            [],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i6.Appointment>>);

  @override
  _i19.Future<List<_i27.TimeSlot>> getAvailability({
    required String? clinicId,
    required String? date,
    String? vetId,
    int? slotDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailability,
          [],
          {
            #clinicId: clinicId,
            #date: date,
            #vetId: vetId,
            #slotDuration: slotDuration,
          },
        ),
        returnValue: _i19.Future<List<_i27.TimeSlot>>.value(<_i27.TimeSlot>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i27.TimeSlot>>.value(<_i27.TimeSlot>[]),
      ) as _i19.Future<List<_i27.TimeSlot>>);

  @override
  _i19.Future<List<_i28.AppointmentHistoryEntry>> getAppointmentHistory(
          String? appointmentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointmentHistory,
          [appointmentId],
        ),
        returnValue: _i19.Future<List<_i28.AppointmentHistoryEntry>>.value(
            <_i28.AppointmentHistoryEntry>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i28.AppointmentHistoryEntry>>.value(
                <_i28.AppointmentHistoryEntry>[]),
      ) as _i19.Future<List<_i28.AppointmentHistoryEntry>>);
}

/// A class which mocks [MedicalRecordService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicalRecordService extends _i1.Mock
    implements _i29.MedicalRecordService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i7.MedicalRecord>> getMedicalRecords({
    int? page = 1,
    int? limit = 20,
    String? petId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMedicalRecords,
          [],
          {
            #page: page,
            #limit: limit,
            #petId: petId,
          },
        ),
        returnValue:
            _i19.Future<_i3.PaginatedResponse<_i7.MedicalRecord>>.value(
                _FakePaginatedResponse_1<_i7.MedicalRecord>(
          this,
          Invocation.method(
            #getMedicalRecords,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i7.MedicalRecord>>.value(
                _FakePaginatedResponse_1<_i7.MedicalRecord>(
          this,
          Invocation.method(
            #getMedicalRecords,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i7.MedicalRecord>>);

  @override
  _i19.Future<_i7.MedicalRecord> getMedicalRecordById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMedicalRecordById,
          [id],
        ),
        returnValue: _i19.Future<_i7.MedicalRecord>.value(_FakeMedicalRecord_5(
          this,
          Invocation.method(
            #getMedicalRecordById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i7.MedicalRecord>.value(_FakeMedicalRecord_5(
          this,
          Invocation.method(
            #getMedicalRecordById,
            [id],
          ),
        )),
      ) as _i19.Future<_i7.MedicalRecord>);

  @override
  _i19.Future<_i7.MedicalRecord> createMedicalRecord(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMedicalRecord,
          [data],
        ),
        returnValue: _i19.Future<_i7.MedicalRecord>.value(_FakeMedicalRecord_5(
          this,
          Invocation.method(
            #createMedicalRecord,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i7.MedicalRecord>.value(_FakeMedicalRecord_5(
          this,
          Invocation.method(
            #createMedicalRecord,
            [data],
          ),
        )),
      ) as _i19.Future<_i7.MedicalRecord>);

  @override
  _i19.Future<_i7.MedicalRecord> updateMedicalRecord(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMedicalRecord,
          [
            id,
            data,
          ],
        ),
        returnValue: _i19.Future<_i7.MedicalRecord>.value(_FakeMedicalRecord_5(
          this,
          Invocation.method(
            #updateMedicalRecord,
            [
              id,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i7.MedicalRecord>.value(_FakeMedicalRecord_5(
          this,
          Invocation.method(
            #updateMedicalRecord,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i7.MedicalRecord>);

  @override
  _i19.Future<void> deleteMedicalRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMedicalRecord,
          [id],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<List<_i7.MedicalRecord>> getPetMedicalRecords(String? petId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPetMedicalRecords,
          [petId],
        ),
        returnValue:
            _i19.Future<List<_i7.MedicalRecord>>.value(<_i7.MedicalRecord>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i7.MedicalRecord>>.value(<_i7.MedicalRecord>[]),
      ) as _i19.Future<List<_i7.MedicalRecord>>);
}

/// A class which mocks [PrescriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrescriptionService extends _i1.Mock
    implements _i30.PrescriptionService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i8.Prescription>> getPrescriptions({
    int? page = 1,
    int? limit = 20,
    String? petId,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrescriptions,
          [],
          {
            #page: page,
            #limit: limit,
            #petId: petId,
            #isActive: isActive,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i8.Prescription>>.value(
            _FakePaginatedResponse_1<_i8.Prescription>(
          this,
          Invocation.method(
            #getPrescriptions,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
              #isActive: isActive,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i8.Prescription>>.value(
                _FakePaginatedResponse_1<_i8.Prescription>(
          this,
          Invocation.method(
            #getPrescriptions,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
              #isActive: isActive,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i8.Prescription>>);

  @override
  _i19.Future<_i8.Prescription> getPrescriptionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrescriptionById,
          [id],
        ),
        returnValue: _i19.Future<_i8.Prescription>.value(_FakePrescription_6(
          this,
          Invocation.method(
            #getPrescriptionById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i8.Prescription>.value(_FakePrescription_6(
          this,
          Invocation.method(
            #getPrescriptionById,
            [id],
          ),
        )),
      ) as _i19.Future<_i8.Prescription>);

  @override
  _i19.Future<_i8.Prescription> createPrescription(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPrescription,
          [data],
        ),
        returnValue: _i19.Future<_i8.Prescription>.value(_FakePrescription_6(
          this,
          Invocation.method(
            #createPrescription,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i8.Prescription>.value(_FakePrescription_6(
          this,
          Invocation.method(
            #createPrescription,
            [data],
          ),
        )),
      ) as _i19.Future<_i8.Prescription>);

  @override
  _i19.Future<_i8.Prescription> updatePrescription(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrescription,
          [
            id,
            data,
          ],
        ),
        returnValue: _i19.Future<_i8.Prescription>.value(_FakePrescription_6(
          this,
          Invocation.method(
            #updatePrescription,
            [
              id,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i8.Prescription>.value(_FakePrescription_6(
          this,
          Invocation.method(
            #updatePrescription,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i8.Prescription>);

  @override
  _i19.Future<void> deletePrescription(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePrescription,
          [id],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i31.Uint8List> downloadPrescriptionPdf(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadPrescriptionPdf,
          [id],
        ),
        returnValue: _i19.Future<_i31.Uint8List>.value(_i31.Uint8List(0)),
        returnValueForMissingStub:
            _i19.Future<_i31.Uint8List>.value(_i31.Uint8List(0)),
      ) as _i19.Future<_i31.Uint8List>);

  @override
  _i19.Future<List<_i8.Prescription>> getPetPrescriptions(String? petId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPetPrescriptions,
          [petId],
        ),
        returnValue:
            _i19.Future<List<_i8.Prescription>>.value(<_i8.Prescription>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i8.Prescription>>.value(<_i8.Prescription>[]),
      ) as _i19.Future<List<_i8.Prescription>>);
}

/// A class which mocks [VaccinationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaccinationService extends _i1.Mock
    implements _i32.VaccinationService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i9.Vaccination>> getVaccinations({
    int? page = 1,
    int? limit = 20,
    String? petId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVaccinations,
          [],
          {
            #page: page,
            #limit: limit,
            #petId: petId,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i9.Vaccination>>.value(
            _FakePaginatedResponse_1<_i9.Vaccination>(
          this,
          Invocation.method(
            #getVaccinations,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i9.Vaccination>>.value(
                _FakePaginatedResponse_1<_i9.Vaccination>(
          this,
          Invocation.method(
            #getVaccinations,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i9.Vaccination>>);

  @override
  _i19.Future<_i9.Vaccination> getVaccinationById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVaccinationById,
          [id],
        ),
        returnValue: _i19.Future<_i9.Vaccination>.value(_FakeVaccination_7(
          this,
          Invocation.method(
            #getVaccinationById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i9.Vaccination>.value(_FakeVaccination_7(
          this,
          Invocation.method(
            #getVaccinationById,
            [id],
          ),
        )),
      ) as _i19.Future<_i9.Vaccination>);

  @override
  _i19.Future<_i9.Vaccination> createVaccination(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVaccination,
          [data],
        ),
        returnValue: _i19.Future<_i9.Vaccination>.value(_FakeVaccination_7(
          this,
          Invocation.method(
            #createVaccination,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i9.Vaccination>.value(_FakeVaccination_7(
          this,
          Invocation.method(
            #createVaccination,
            [data],
          ),
        )),
      ) as _i19.Future<_i9.Vaccination>);

  @override
  _i19.Future<_i9.Vaccination> updateVaccination(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVaccination,
          [
            id,
            data,
          ],
        ),
        returnValue: _i19.Future<_i9.Vaccination>.value(_FakeVaccination_7(
          this,
          Invocation.method(
            #updateVaccination,
            [
              id,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i9.Vaccination>.value(_FakeVaccination_7(
          this,
          Invocation.method(
            #updateVaccination,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i9.Vaccination>);

  @override
  _i19.Future<void> deleteVaccination(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVaccination,
          [id],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<List<_i9.Vaccination>> getPetVaccinations(String? petId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPetVaccinations,
          [petId],
        ),
        returnValue:
            _i19.Future<List<_i9.Vaccination>>.value(<_i9.Vaccination>[]),
        returnValueForMissingStub:
            _i19.Future<List<_i9.Vaccination>>.value(<_i9.Vaccination>[]),
      ) as _i19.Future<List<_i9.Vaccination>>);
}

/// A class which mocks [DocumentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentService extends _i1.Mock implements _i33.DocumentService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i10.Document>> getDocuments({
    int? page = 1,
    int? limit = 20,
    String? petId,
    String? medicalRecordId,
    String? documentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocuments,
          [],
          {
            #page: page,
            #limit: limit,
            #petId: petId,
            #medicalRecordId: medicalRecordId,
            #documentType: documentType,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i10.Document>>.value(
            _FakePaginatedResponse_1<_i10.Document>(
          this,
          Invocation.method(
            #getDocuments,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
              #medicalRecordId: medicalRecordId,
              #documentType: documentType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i10.Document>>.value(
                _FakePaginatedResponse_1<_i10.Document>(
          this,
          Invocation.method(
            #getDocuments,
            [],
            {
              #page: page,
              #limit: limit,
              #petId: petId,
              #medicalRecordId: medicalRecordId,
              #documentType: documentType,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i10.Document>>);

  @override
  _i19.Future<_i10.Document> getDocumentById(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentById,
          [documentId],
        ),
        returnValue: _i19.Future<_i10.Document>.value(_FakeDocument_8(
          this,
          Invocation.method(
            #getDocumentById,
            [documentId],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i10.Document>.value(_FakeDocument_8(
          this,
          Invocation.method(
            #getDocumentById,
            [documentId],
          ),
        )),
      ) as _i19.Future<_i10.Document>);

  @override
  _i19.Future<_i10.Document> uploadDocument({
    required _i34.File? file,
    required String? petId,
    required String? documentType,
    required String? title,
    String? description,
    String? medicalRecordId,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadDocument,
          [],
          {
            #file: file,
            #petId: petId,
            #documentType: documentType,
            #title: title,
            #description: description,
            #medicalRecordId: medicalRecordId,
            #tags: tags,
          },
        ),
        returnValue: _i19.Future<_i10.Document>.value(_FakeDocument_8(
          this,
          Invocation.method(
            #uploadDocument,
            [],
            {
              #file: file,
              #petId: petId,
              #documentType: documentType,
              #title: title,
              #description: description,
              #medicalRecordId: medicalRecordId,
              #tags: tags,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i10.Document>.value(_FakeDocument_8(
          this,
          Invocation.method(
            #uploadDocument,
            [],
            {
              #file: file,
              #petId: petId,
              #documentType: documentType,
              #title: title,
              #description: description,
              #medicalRecordId: medicalRecordId,
              #tags: tags,
            },
          ),
        )),
      ) as _i19.Future<_i10.Document>);

  @override
  _i19.Future<_i10.Document> updateDocument(
    String? documentId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [
            documentId,
            data,
          ],
        ),
        returnValue: _i19.Future<_i10.Document>.value(_FakeDocument_8(
          this,
          Invocation.method(
            #updateDocument,
            [
              documentId,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i10.Document>.value(_FakeDocument_8(
          this,
          Invocation.method(
            #updateDocument,
            [
              documentId,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i10.Document>);

  @override
  _i19.Future<void> deleteDocument(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<String> downloadDocument(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadDocument,
          [documentId],
        ),
        returnValue: _i19.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #downloadDocument,
            [documentId],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #downloadDocument,
            [documentId],
          ),
        )),
      ) as _i19.Future<String>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i35.UserService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i2.User>> getUsers({
    int? page = 1,
    int? limit = 20,
    String? role,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
          {
            #page: page,
            #limit: limit,
            #role: role,
            #isActive: isActive,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i2.User>>.value(
            _FakePaginatedResponse_1<_i2.User>(
          this,
          Invocation.method(
            #getUsers,
            [],
            {
              #page: page,
              #limit: limit,
              #role: role,
              #isActive: isActive,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i2.User>>.value(
                _FakePaginatedResponse_1<_i2.User>(
          this,
          Invocation.method(
            #getUsers,
            [],
            {
              #page: page,
              #limit: limit,
              #role: role,
              #isActive: isActive,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i2.User>>);

  @override
  _i19.Future<_i2.User> getUserById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValue: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
      ) as _i19.Future<_i2.User>);

  @override
  _i19.Future<_i2.User> createUser(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [data],
        ),
        returnValue: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #createUser,
            [data],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #createUser,
            [data],
          ),
        )),
      ) as _i19.Future<_i2.User>);

  @override
  _i19.Future<_i2.User> updateUser(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            id,
            data,
          ],
        ),
        returnValue: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateUser,
            [
              id,
              data,
            ],
          ),
        )),
        returnValueForMissingStub: _i19.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateUser,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i2.User>);

  @override
  _i19.Future<void> deactivateUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deactivateUser,
          [id],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i11.BulkCreateResult> bulkCreateUsers(
          List<Map<String, dynamic>>? users) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkCreateUsers,
          [users],
        ),
        returnValue:
            _i19.Future<_i11.BulkCreateResult>.value(_FakeBulkCreateResult_9(
          this,
          Invocation.method(
            #bulkCreateUsers,
            [users],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i11.BulkCreateResult>.value(_FakeBulkCreateResult_9(
          this,
          Invocation.method(
            #bulkCreateUsers,
            [users],
          ),
        )),
      ) as _i19.Future<_i11.BulkCreateResult>);
}

/// A class which mocks [ClinicService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClinicService extends _i1.Mock implements _i36.ClinicService {
  @override
  _i19.Future<_i12.Clinic> getClinicInfo() => (super.noSuchMethod(
        Invocation.method(
          #getClinicInfo,
          [],
        ),
        returnValue: _i19.Future<_i12.Clinic>.value(_FakeClinic_10(
          this,
          Invocation.method(
            #getClinicInfo,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i12.Clinic>.value(_FakeClinic_10(
          this,
          Invocation.method(
            #getClinicInfo,
            [],
          ),
        )),
      ) as _i19.Future<_i12.Clinic>);

  @override
  _i19.Future<_i12.Clinic> updateClinicInfo(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClinicInfo,
          [data],
        ),
        returnValue: _i19.Future<_i12.Clinic>.value(_FakeClinic_10(
          this,
          Invocation.method(
            #updateClinicInfo,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i12.Clinic>.value(_FakeClinic_10(
          this,
          Invocation.method(
            #updateClinicInfo,
            [data],
          ),
        )),
      ) as _i19.Future<_i12.Clinic>);

  @override
  _i19.Future<Map<String, dynamic>> getClinicSettings() => (super.noSuchMethod(
        Invocation.method(
          #getClinicSettings,
          [],
        ),
        returnValue:
            _i19.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i19.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i19.Future<Map<String, dynamic>>);

  @override
  _i19.Future<Map<String, dynamic>> updateClinicSettings(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClinicSettings,
          [data],
        ),
        returnValue:
            _i19.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i19.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i19.Future<Map<String, dynamic>>);

  @override
  _i19.Future<_i13.ClinicBranding> getClinicBranding() => (super.noSuchMethod(
        Invocation.method(
          #getClinicBranding,
          [],
        ),
        returnValue:
            _i19.Future<_i13.ClinicBranding>.value(_FakeClinicBranding_11(
          this,
          Invocation.method(
            #getClinicBranding,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i13.ClinicBranding>.value(_FakeClinicBranding_11(
          this,
          Invocation.method(
            #getClinicBranding,
            [],
          ),
        )),
      ) as _i19.Future<_i13.ClinicBranding>);

  @override
  _i19.Future<_i13.ClinicBranding> updateClinicBranding(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClinicBranding,
          [data],
        ),
        returnValue:
            _i19.Future<_i13.ClinicBranding>.value(_FakeClinicBranding_11(
          this,
          Invocation.method(
            #updateClinicBranding,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i13.ClinicBranding>.value(_FakeClinicBranding_11(
          this,
          Invocation.method(
            #updateClinicBranding,
            [data],
          ),
        )),
      ) as _i19.Future<_i13.ClinicBranding>);
}

/// A class which mocks [ReminderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderService extends _i1.Mock implements _i37.ReminderService {
  @override
  _i19.Future<_i3.PaginatedResponse<_i14.Reminder>> getReminders({
    int? page = 1,
    int? limit = 20,
    String? status,
    String? reminderType,
    String? petId,
    String? ownerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReminders,
          [],
          {
            #page: page,
            #limit: limit,
            #status: status,
            #reminderType: reminderType,
            #petId: petId,
            #ownerId: ownerId,
          },
        ),
        returnValue: _i19.Future<_i3.PaginatedResponse<_i14.Reminder>>.value(
            _FakePaginatedResponse_1<_i14.Reminder>(
          this,
          Invocation.method(
            #getReminders,
            [],
            {
              #page: page,
              #limit: limit,
              #status: status,
              #reminderType: reminderType,
              #petId: petId,
              #ownerId: ownerId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i3.PaginatedResponse<_i14.Reminder>>.value(
                _FakePaginatedResponse_1<_i14.Reminder>(
          this,
          Invocation.method(
            #getReminders,
            [],
            {
              #page: page,
              #limit: limit,
              #status: status,
              #reminderType: reminderType,
              #petId: petId,
              #ownerId: ownerId,
            },
          ),
        )),
      ) as _i19.Future<_i3.PaginatedResponse<_i14.Reminder>>);

  @override
  _i19.Future<_i14.Reminder> getReminderById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getReminderById,
          [id],
        ),
        returnValue: _i19.Future<_i14.Reminder>.value(_FakeReminder_12(
          this,
          Invocation.method(
            #getReminderById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i14.Reminder>.value(_FakeReminder_12(
          this,
          Invocation.method(
            #getReminderById,
            [id],
          ),
        )),
      ) as _i19.Future<_i14.Reminder>);

  @override
  _i19.Future<_i14.Reminder> createReminder(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReminder,
          [data],
        ),
        returnValue: _i19.Future<_i14.Reminder>.value(_FakeReminder_12(
          this,
          Invocation.method(
            #createReminder,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i14.Reminder>.value(_FakeReminder_12(
          this,
          Invocation.method(
            #createReminder,
            [data],
          ),
        )),
      ) as _i19.Future<_i14.Reminder>);

  @override
  _i19.Future<_i14.Reminder> updateReminder(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReminder,
          [
            id,
            data,
          ],
        ),
        returnValue: _i19.Future<_i14.Reminder>.value(_FakeReminder_12(
          this,
          Invocation.method(
            #updateReminder,
            [
              id,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i14.Reminder>.value(_FakeReminder_12(
          this,
          Invocation.method(
            #updateReminder,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i19.Future<_i14.Reminder>);

  @override
  _i19.Future<void> deleteReminder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReminder,
          [id],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i15.SendResult> sendPendingReminders() => (super.noSuchMethod(
        Invocation.method(
          #sendPendingReminders,
          [],
        ),
        returnValue: _i19.Future<_i15.SendResult>.value(_FakeSendResult_13(
          this,
          Invocation.method(
            #sendPendingReminders,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<_i15.SendResult>.value(_FakeSendResult_13(
          this,
          Invocation.method(
            #sendPendingReminders,
            [],
          ),
        )),
      ) as _i19.Future<_i15.SendResult>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i38.ConnectivityService {
  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i19.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<bool> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i19.Future<bool>.value(false),
        returnValueForMissingStub: _i19.Future<bool>.value(false),
      ) as _i19.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImageUploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageUploadService extends _i1.Mock
    implements _i39.ImageUploadService {
  @override
  _i19.Future<_i34.File?> pickAndCropImage({
    required _i40.ImageSource? source,
    double? maxWidth = 1024.0,
    double? maxHeight = 1024.0,
    _i41.CropAspectRatio? aspectRatio,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickAndCropImage,
          [],
          {
            #source: source,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #aspectRatio: aspectRatio,
          },
        ),
        returnValue: _i19.Future<_i34.File?>.value(),
        returnValueForMissingStub: _i19.Future<_i34.File?>.value(),
      ) as _i19.Future<_i34.File?>);

  @override
  _i19.Future<String> uploadPetPhoto(
    String? petId,
    _i34.File? imageFile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPetPhoto,
          [
            petId,
            imageFile,
          ],
        ),
        returnValue: _i19.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #uploadPetPhoto,
            [
              petId,
              imageFile,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #uploadPetPhoto,
            [
              petId,
              imageFile,
            ],
          ),
        )),
      ) as _i19.Future<String>);

  @override
  _i19.Future<String> uploadAvatar(_i34.File? imageFile) => (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [imageFile],
        ),
        returnValue: _i19.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [imageFile],
          ),
        )),
        returnValueForMissingStub:
            _i19.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [imageFile],
          ),
        )),
      ) as _i19.Future<String>);
}
